// axi-sdk-js managed opencode plugin: hevy-axi
// This file is generated by `hevy-axi setup hooks`. It is safe to edit only if you remove the managed marker above.
import { spawn } from "node:child_process";

const command = {{COMMAND}};
const marker = "hevy-axi";
const ambientHeader = "## AXI ambient context: hevy-axi";
const timeoutMs = 10000;

function runAxiHomeView(cwd) {
  return new Promise((resolve) => {
    const child = spawn(command, [], {
      cwd: directoryOrFallback(cwd),
      env: process.env,
      shell: false,
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let settled = false;

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      child.kill("SIGTERM");
      resolve("error: " + marker + " ambient context timed out after " + timeoutMs + "ms");
    }, timeoutMs);

    child.stdout?.setEncoding("utf-8");
    child.stderr?.setEncoding("utf-8");
    child.stdout?.on("data", (chunk) => {
      stdout += chunk;
    });
    child.stderr?.on("data", (chunk) => {
      stderr += chunk;
    });
    child.on("error", (error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve("error: " + marker + " ambient context failed: " + error.message);
    });
    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (code === 0) {
        resolve(stdout.trim());
        return;
      }
      const message = (stderr || stdout || marker + " exited with code " + code).trim();
      resolve("error: " + marker + " ambient context failed: " + message);
    });
  });
}

function directoryOrFallback(directory) {
  return typeof directory === "string" && directory.length > 0
    ? directory
    : process.cwd();
}

// Returns the session's ambient context text, running the AXI home view once per session.
function ambientContextFor(directory) {
  const sessionCache = new Map();

  return async (sessionID) => {
    const key = sessionID ?? "__global__";
    let homeView = sessionCache.get(key);
    if (homeView === undefined) {
      homeView = await runAxiHomeView(directory);
      sessionCache.set(key, homeView);
    }
    return homeView.length === 0 ? "" : ambientHeader + "\n" + homeView;
  };
}

export default {
  id: "axi-hevy-axi",
  // OpenCode 2 entrypoint.
  async setup(ctx) {
    const ambientContext = ambientContextFor(ctx.location.directory);
    await ctx.session.hook("context", async (event) => {
      const text = await ambientContext(event.sessionID);
      if (text) event.system.push({ type: "text", text });
    });
  },
  // OpenCode 1 entrypoint.
  async server({ directory }) {
    const ambientContext = ambientContextFor(directory);
    return {
      "experimental.chat.system.transform": async (input, output) => {
        const text = await ambientContext(input.sessionID);
        if (text) output.system.push(text);
      },
    };
  },
};
